### ISSUE TITLE
The info is displayed twice

### ISSUE THREAD

**Issue by Nordblum** [DestroyedClone/PoseHelper#1]
Is there any reason for that? Maybe it's unintentional? [Here's an example](https://i.imgur.com/nrEMIm0.png).

**Comment by DestroyedClone** [comment]
The top value is running on an Update() whereas the lower value is running on a FixedUpdate().
https://stackoverflow.com/questions/34447682/what-is-the-difference-between-update-fixedupdate-in-unity
