### ISSUE TITLE
DoshDrop - Only host can drop money in multiplayer

### ISSUE THREAD

**Issue by herosamuel96** [DestroyedClone/PoseHelper#14]
everyone but the host only can drop their money

**Comment by JamesMDenton** [comment]
Only the host was able to throw money in my games. We even tried swapping hosts, and through multiple swaps, only the host could do it.

**Comment by DestroyedClone** [comment]
Fixed with https://github.com/DestroyedClone/PoseHelper/commit/3e714cfd6a54fd6d4f22cf0d3420d72c973aaf06
