### ISSUE TITLE
Issue: [DD2Lobby] Not Working

### ISSUE THREAD

**Issue by L-Ratio** [DestroyedClone/PoseHelper#15]
**Describe the bug**
It does not load the lobby aka the lobby stays the same as default 

**To Reproduce**
1.  Download the mod
2. Start ROR2
3.  Enter any lobby

**Expected behavior**
The lobby changes

**Comment by piebaker** [comment]
Just confirming, is this still the case with DD2Lobby? Would love to use this for me any my friends personally.

**Comment by DestroyedClone** [comment]
SOTV did some lobby changes, so I have to look into how far things are changed. I know they moved to a "SurvivorMannequins" or something type component.

**Comment by DestroyedClone** [comment]
Fixed in new repository: https://github.com/DestroyedClone/ROR2DD2Lobby and with latest release on thunderstore
