### ISSUE TITLE
Issue: FasterPickupText doesn't work anymore

### ISSUE THREAD

**Issue by SegoItCh** [DestroyedClone/PoseHelper#19]
[Info   :   BepInEx] Loading [Faster Pickup Text 1.0.0]
[Error  : Unity Log] MissingFieldException: Field 'RoR2.UI.GenericNotification.duration' not found.
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
FlashWindow:.cctor()

**Comment by DestroyedClone** [comment]
SOTV changed how pickup notifications work, so the mod needs to be rewritten to accommodate these changes.

**Comment by DestroyedClone** [comment]
Fixed with commit https://github.com/DestroyedClone/PoseHelper/commit/9359ac327678f26ed3d57fab2171ee11b3715e29
