### ISSUE TITLE
Suggestion: [MonsterTeamSwap] Add Void Team to config

### ISSUE THREAD

**Issue by CerbsUp** [DestroyedClone/PoseHelper#27]
So Theres No Void Team In The Config And I Would Appreciate It Very Much If There Was

**Comment by CerbsUp** [comment]
So Theres No Void Team And I Would Appreciate It Very Much If There Was

**Comment by DestroyedClone** [comment]
Added with https://github.com/DestroyedClone/PoseHelper/commit/71800d8d695c6d499b30a1ec58a12854d3705c80
