### ISSUE TITLE
Suggestion: [HealthbarImmune] per character configs

### ISSUE THREAD

**Issue by CatsArmy** [DestroyedClone/PoseHelper#31]
add configs for each character to disable the mod on them as some mods implement custom bars which  (im guessing uses the health bar as a base which) then breaks when healthbarimmune is installed it may be purely visual but its still annoys me so I thought it wont hurt to suggest a lil suggestion

im unsure of how possiable this is but yeee (sorry if this was allready suggested which i don think it was)

**Comment by DestroyedClone** [comment]
Added https://github.com/DestroyedClone/PoseHelper/commit/aa3f4094df76a9ec08d3c40ba40666cad4d4a870
