### ISSUE TITLE
Issue: [SunDimmer] WellRoundedBalance's planula sun isn't affected

### ISSUE THREAD

**Issue by LordVGames** [DestroyedClone/PoseHelper#34]
**Describe the bug**
WRB's planula rework makes it summon a grandparent sun above you. It should be affected by SunDimmer, but isn't.

**To Reproduce**
1. Stand still to summon the sun from planula
2. See the light from it still bright as hell

**Expected behavior**
The lighting from the sun isn't super bright.

**Additional context**
Paladin's sun (changed by the mod):

![image](https://github.com/DestroyedClone/PoseHelper/assets/51967559/9dec6cca-b726-4cef-ad2f-7856fe35fef3)

WRB planula's sun (not changed):

![image](https://github.com/DestroyedClone/PoseHelper/assets/51967559/6cef2ae5-5318-4d93-b710-e0fd915e89a6)

**Comment by DestroyedClone** [comment]
SunDimmer reduces the brightness of the Light component attached to the sun's prefab. PaladinMod just copies the grandparent's sun just to control the mechanical effects. WRB (https://github.com/hifoomin/WellRoundedBalance/blob/master/Content/Items/Yellows/Planula.cs#L24-L36) sets the color grading and bloom of the postprocess profile.

**Comment by LordVGames** [comment]
So it's not a bug with sundimmer since WRB sets up the sun different from vanilla + paladin, didn't know that.
