### ISSUE TITLE
Issue: [Speedometer] Hides the UI. Cannot be fixed unless mod is disabled.

### ISSUE THREAD

**Issue by DunZek** [DestroyedClone/PoseHelper#35]
**Describe the bug**
- Hides the UI; no UI element appears when game starts and the vanilla setting option does not fix this issue.
- Use my mod profile.
- Have not been reproduced in other mod profiles/computers.
- Game version 1.2.4.4

**To Reproduce**
1. Use my profile.
2. Simply start a game (go from character selection to stage 1).

**Expected behavior**
- Show a speedometer UI element.

**Additional context**
[Modded for QOL improvements_1711956710316.zip](https://github.com/DestroyedClone/PoseHelper/files/14820902/Modded.for.QOL.improvements_1711956710316.zip)

- Use my mod profile.
- Have not been reproduced in other mod profiles/computers.
- The vanilla setting option neither affects nor fixes this bug.
- Game version 1.2.4.4

**Comment by DestroyedClone** [comment]
As of Devotion update or earlier, the HUD prefab no longer has Speedometer, thus the mod is unable to activate something that has been removed. Mod has been deprecated.
