### ISSUE TITLE
NoHereticTransform: Config to make it only transform if you also pick up Beads of Fealty

### ISSUE THREAD

**Issue by gaforb** [DestroyedClone/PoseHelper#8]
idk seems like a fun idea

**Comment by DestroyedClone** [comment]
Added to v1.0.1 of the mod.
Github Change: https://github.com/DestroyedClone/PoseHelper/commit/4b1c4b82727625e65ef7e96f966b74f1d9979156#diff-80063fddf738eb471b814a46b436fa9f9bb2a4ceee573116e9972d83f0074a77
Thunderstore: https://thunderstore.io/package/DestroyedClone/NoHereticTransform/1.0.1/
